### PR TITLE
Support for Plaid Investments Product

### PR DESCRIPTION
**Pull request by cblage**
This PR adds support for the Plaid Investments Product.

I tried following the existing structure, let me know what you think :)

Fixes https://github.com/wfgilman/plaid-elixir/issues/29 (and in case you're wondering, @aloukissas and I work together 😄 - he created the issue)

### CODE REVIEW

**Comment by wfgilman** [comment]
@cblage thanks for the PR! I look this guys over and made some file structure changes to unpack the `investments.ex` file. I pulled `Plaid.Investments.Security` into its own file and separated `Plaid.Investments.Holdings` and `Plaid.Investments.Transactions` into their own files. All three are organized under `plaid/investments` folder. I also moved the order of certain declarations, like grouping all `@type`s together. The changes are here: https://github.com/wfgilman/plaid-elixir/pull/31

All the test pass but you should check it out to make sure it still works for you.

**Comment by cblage** [comment]
@wfgilman looks good to me 😄 I considered doing this split myself, but I went ahead and kept it as close as possible as the rest of the codebase.

**Comment by cblage** [comment]
Closing in favor https://github.com/wfgilman/plaid-elixir/pull/31

**Comment by wfgilman** [comment]
Sweet! I’ll merge it as soon as I get home tonight.

**Pull request closed without merging**
