### PR TITLE
setup asset report

### PR DESCRIPTION
**Pull request by allenwyma**

### CODE REVIEW

**Comment by wfgilman** [comment]
Thanks for the PR! I made a few comments to identify some potential errors and design suggestions to keep the library's pattern consistent.

**Comment by HangingClowns** [comment]
Hi @wfgilman maybe I missed something but I don’t see your comments.

**Comment by wfgilman** [comment]
They’re annotated on the files changed.

**Comment by HangingClowns** [comment]
Hi,

I still don't see it. Usually people would make comments on the files changed section of the PR and also they will show up on here.

Do you mind to send me a link to it? Cause I also checked my repo but I didn't see any comments at all.

**Review by wfgilman — COMMENTED** [review]
@HangingClowns can you see this? Maybe I was supposed to hit the Review Changes button

**Comment by wfgilman** [comment]
Handled by https://github.com/wfgilman/plaid-elixir/pull/81

**Pull request closed without merging**
