### PR TITLE
update transactions & link / add payment initiation

### PR DESCRIPTION
**Pull request by agramichael**
- update transactions data structure
- update link data structure and add get_link_token
- add payment initiation support (recipients and payments)

### CODE REVIEW

**Comment by wfgilman** [comment]
@agramichael looks like there's some breaking changes here with the removal of some fields from the `Plaid.Link`struct. Could you link me to the Plaid API docs on this?

**Comment by agramichael** [comment]
@wfgilman Sure, here you go: https://plaid.com/docs/api/tokens/#linktokencreate

**Comment by agramichael** [comment]
any updates on this?

**Comment by wfgilman** [comment]
@agramichael incorporated your changes with https://github.com/wfgilman/plaid-elixir/pull/57. I added back a few deleted struct fields so as not to introduce breaking changes. Add a deprecated note that Plaid migrated from these fields.

**Pull request closed without merging**
