### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
List of changes:
* Use common source url
* Use and set latest ex_doc
* Set readme as main html page
* Refactor project config
* Update gitignore
* Fix typos
* Badges and more badges!
* Tally minimum Elixir version with Travis CI version
* Add license section
* Generate only html output
* Move logo to standard location

### CODE REVIEW

**Comment by kianmeng** [comment]
@wfgilman Should I resolve the conflict and resubmit the PR?

**Comment by wfgilman** [comment]
Thanks for the PR, Ang. Your edits have some breaking changes with respect
to dependency upgrades and the min Elixir version which is why I didn't
merge it (in addition to the merge conflicts).

**Comment by kianmeng** [comment]
> Thanks for the PR, Ang. Your edits have some breaking changes with respect to dependency upgrades and the min Elixir version which is why I didn't merge it (in addition to the merge conflicts).

@wfgilman Thanks for letting me know. Should the minimum Elixir requirements matches the minimum version in the Travis CI? I remembered that was the reason I bumped it in `mix.exs`.

See https://github.com/wfgilman/plaid-elixir/blob/master/.travis.yml

```yaml
elixir:
  - 1.7.4
  - 1.8.0
```

**Comment by wfgilman** [comment]
@kianmeng that's just for the git CI, but I don't want to break anyone's integration who's running on 1.5. Thanks 🙂

**Comment by kianmeng** [comment]
@wfgilman Noted, and I've amended the changes. Let me know if there are any other changes.

**Comment by kianmeng** [comment]
:tada: :tada: :tada: :tada: :tada:

**Pull request merged**
